# Generated by Django 3.1 on 2020-09-09 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boards', '0002_board_created_dt'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
